version: "3.8"

services:
  app:
    image: php82-nginx:1.0
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php.ini:/usr/local/etc/php/php.ini
      # - ./supervisord.conf:/etc/supervisor/supervisord.conf:ro
    environment:
      APP_ENV: local
      TZ: Asia/Jakarta
