version: "3.8"

services:
  app:
    image: php74-nginx:base
    container_name: php74-nginx-app
    restart: unless-stopped
    ports:
      - "8074:80"
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php.ini:/usr/local/etc/php/php.ini

    environment:
      APP_ENV: local
      TZ: Asia/Jakarta
